### PR TITLE
moved button click listener from auth.js to app.js

### PR DESCRIPTION
**Pull request by burke1791**

### CODE REVIEW

**Review by jlouie10 — CHANGES_REQUESTED** [review]
Chris, the branch isn't working for me, but I see why. You turned the button on click event into an on click event that targets the signInButton class. This is 100% the right move, but the class is wrong. 

What I think we need to do is create a new class and add it to each of the sign in and sign up buttons that are inside the modal. For example,
```
# index.html
115 <button type="submit" class="btn btn-primary some-new-class" value="signin">Sign In</button>
    ...
132 <button type="submit" class="btn btn-primary some-new-class" value="signup">Sign Up</button>
```
and
```
$(".some-new-class").on("click", function (event) {...}
```

**Comment by jlouie10** [comment]
The background for this is that I created a general button on click event listener for the sign in and sign up buttons on the form. I added the modal later, but the logic made it so that there was no functional impact (the function would just run when it didn't need to). 

We need the reference to be more specific, so your turning it into a class is right. But the class you selected is one that Tony added to the button that activates the modal. So a new class needs to be added.

**Comment by burke1791** [comment]
My mistake, totally missed that in testing.  I agree with your comments and will update it this evening when I get home from work.  If you need/want it merged sooner, feel free to update the branch yourself.

**Comment by burke1791** [comment]
Updated the branch and should be working as expected.  Let me know if that's not the case.

**Review by jlouie10 — APPROVED** [review]
Looks good!

**Pull request merged**
