### PR TITLE
Authenticate user

### PR DESCRIPTION
**Pull request by jlouie10**
Added button to menu bar that launches modal. Modal contains 2 tabs: "sign in" and "sign up." Modal uses Firebase integration to create users and log them in using a session.

### CODE REVIEW

**Review by burke1791 — CHANGES_REQUESTED** [review]
sign up action is overwriting the users node

**Comment by jlouie10** [comment]
Modified reference: 

```
obj = { email: email };

database.ref("users/" + uid + "/").set(obj);
```

**Review by burke1791 — APPROVED** [review]
Looks good.

**Comment by jlouie10** [comment]
Merged, no going back!

**Pull request merged**
